services:
  - type: web
    name: antamclinic
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: ./entrypoint.sh  # Hoặc "gunicorn run:app" nếu không cần setup/seed
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: antamclinic-db
          property: connectionString
      - key: SECRET_KEY  # Thêm env vars cần thiết
        value: your_random_secret_key  # Generate random, không hardcode
      - key: MAIL_USERNAME
        value: xuanhuy9a9@gmail.com
      - key: MAIL_PASSWORD
        value: 14112002  # Sử dụng Render's secret vars để tránh leak

databases:
  - name: antamclinic-db
    plan: free
    region: oregon
    postgresqlMajorVersion: 16
    databaseName: antamclinic  # Optional, default random
    user: admin_user  # Optional
    storage: 1
    highAvailability: false
    storageAutoscaling: false