services:
  - type: web
    name: antamclinic
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: bash ./entrypoint.sh  # Sử dụng bash để chạy script, đảm bảo entrypoint.sh được thực thi
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: antamclinic-db
          property: connectionString
      - key: SECRET_KEY
        value: your_random_secret_key_here  # Thay bằng key ngẫu nhiên mạnh (chạy local: python -c 'import secrets; print(secrets.token_hex(16))')
      - key: MAIL_USERNAME
        value: your_email@gmail.com  # Thay bằng email thật
      - key: MAIL_PASSWORD
        sync: false  # Thêm mật khẩu qua dashboard để an toàn, không commit Git

databases:
  - name: antamclinic-db
    plan: free
    region: oregon
    postgresqlMajorVersion: 16
    databaseName: antamclinic  # Optional
    user: admin_user  # Optional
    storage: 1
    highAvailability: false
    storageAutoscaling: false